version: '3.5'


services:

  db:
    build: ./
    container_name: pgvector
    #restart: always
    #platform: linux/amd64
    shm_size: '128mb'

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: most_basic_chatbot
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 54323:5432
    volumes:
      - type: volume
        source: postgreslib
        target: /var/lib/postgresql/data
volumes:
  postgreslib:
    name: most-basic-chatbot-pg